// src/core/devmode-blob.js
// AUTO-GENERATED by scripts/gen-devmode.js — DO NOT EDIT MANUALLY
// 重新生成：修改 scripts/gen-devmode.js 中的 DEV_PASSWORD / DEV_CONFIG 后运行 node scripts/gen-devmode.js
export const DEV_BLOB = {
  saltB64: "WbhvTSzq7jX1bYQyNs5KSQ==",
  ivB64: "KoYwUmOXYammoVAi",
  ctB64: "za37BMXQXCHLL3W45LSuNy+pMLXWjaqR0svInBDIJc4KzpISbs1RrhM2ZP88Q0PlpbonUaU9o7XWcJTkfOrN5KhAsu8OfvAYbY9pUfxOKflhQWgx3SJJfQnOKOEYKFoTksfwlHzKZdNPlqumjREKDlWQpXuFbZI/63O66KY/Ww9NVK+4JGgR6a/sw0gSqY/QIDUv1EGngwZOkxrGxg13o1fDMml+v6+hKBoCFAAOj7QSCt2+MzF+YP/qzmE/Q1LoznQplmOkPnTGItbIrGvJMd5/m/6XAxyx0Vz4cs379g==",
  pwHash: "29bd1a86cd27bbe3ded241e6c810a7ac17f18a5f90f9de976e7918494e4aba7c",
  iterations: 310000,
};
