// scripts/gen-devmode.example.js
// 生成开发者模式的加密配置 blob（AES-256-GCM + PBKDF2，与浏览器 WebCrypto 完全兼容）
//
// 这是 gen-devmode.js 的脱敏模板：把本文件复制成 scripts/gen-devmode.js，
// 填入自己的密码与 LLM 配置后运行 `node scripts/gen-devmode.js` 即可重新生成 blob。
//
//   cp scripts/gen-devmode.example.js scripts/gen-devmode.js
//   # 编辑 DEV_PASSWORD / DEV_CONFIG
//   node scripts/gen-devmode.js
//
// 输出：src/core/devmode-blob.js （自动生成，勿手改；该文件随仓库提交，源码里只含密文）
//
// ⚠️ gen-devmode.js 含明文密码与 API Key，已被 .gitignore 忽略，切勿提交。
import { webcrypto as crypto } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ========== 在这里改密码和配置 ==========
const DEV_PASSWORD = 'REPLACE-WITH-YOUR-STRONG-PASSWORD';
const DEV_CONFIG = {
  name: 'Agnes Dev',
  baseUrl: 'https://api.agnes-ai.cn/v1',
  apiKey: 'sk-YOUR-LLM-API-KEY',
  model: 'agnes-3.0-flash',
  visionModel: 'agnes-3.0-flash',
  reasoningEffort: 'medium', // low | medium | high
};
// ========================================

const PBKDF2_ITERATIONS = 310_000; // OWASP 2022+ 建议 ≥310k

// 可选的固定 salt/iv（base64）。默认 null = 每次生成随机。
// 用途：需要复现已发布的 blob 时填入原值，可做到逐字节一致。
const FIXED_SALT_B64 = null;
const FIXED_IV_B64 = null;

// 校验哈希 = SHA-256(PBKDF2 派生密钥的原始字节)。
// 攻击者每验证一个候选密码都必须先跑完 310k 次 PBKDF2 迭代，
// 离线字典攻击速度从「每秒数十亿」压到「每秒数千」。
//
// ⚠️ 必须与 src/core/devmode.js 的解锁逻辑保持一致，改一处要同步改另一处。

const enc = new TextEncoder();
const b64 = (u8) => Buffer.from(u8).toString('base64');
const b64ToU8 = (s) => Uint8Array.from(Buffer.from(s, 'base64'));
const hex = (u8) => [...u8].map(b => b.toString(16).padStart(2, '0')).join('');

async function deriveViaPassword(password, salt, iterations) {
  const keyMaterial = await crypto.subtle.importKey('raw', enc.encode(password), 'PBKDF2', false, ['deriveBits']);
  const rawBits = new Uint8Array(await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations, hash: 'SHA-256' },
    keyMaterial,
    256
  ));
  return rawBits;
}

async function main() {
  const salt = FIXED_SALT_B64 ? b64ToU8(FIXED_SALT_B64) : crypto.getRandomValues(new Uint8Array(16));
  const iv = FIXED_IV_B64 ? b64ToU8(FIXED_IV_B64) : crypto.getRandomValues(new Uint8Array(12));

  // ---- 加密 ----
  const rawBits = await deriveViaPassword(DEV_PASSWORD, salt, PBKDF2_ITERATIONS);
  const key = await crypto.subtle.importKey('raw', rawBits, { name: 'AES-GCM' }, false, ['encrypt']);
  const plaintext = enc.encode(JSON.stringify(DEV_CONFIG));
  const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, plaintext));

  // 校验哈希挂在慢哈希之后：SHA-256(派生密钥原始字节)
  const pwHash = hex(new Uint8Array(await crypto.subtle.digest('SHA-256', rawBits)));

  const out = `// src/core/devmode-blob.js
// AUTO-GENERATED by scripts/gen-devmode.js — DO NOT EDIT MANUALLY
// 重新生成：修改 scripts/gen-devmode.js 中的 DEV_PASSWORD / DEV_CONFIG 后运行 node scripts/gen-devmode.js
export const DEV_BLOB = {
  saltB64: ${JSON.stringify(b64(salt))},
  ivB64: ${JSON.stringify(b64(iv))},
  ctB64: ${JSON.stringify(b64(ct))},
  pwHash: ${JSON.stringify(pwHash)},
  iterations: ${PBKDF2_ITERATIONS},
};
`;

  // ---- 自检：把刚生成的 blob 当作"浏览器端"再解一遍 ----
  const verifyRawBits = await deriveViaPassword(DEV_PASSWORD, b64ToU8(b64(salt)), PBKDF2_ITERATIONS);
  const verifyHash = hex(new Uint8Array(await crypto.subtle.digest('SHA-256', verifyRawBits)));
  if (verifyHash !== pwHash) throw new Error('自检失败：pwHash 与派生密钥不一致');

  const verifyKey = await crypto.subtle.importKey('raw', verifyRawBits, { name: 'AES-GCM' }, false, ['decrypt']);
  const decrypted = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: b64ToU8(b64(iv)) }, verifyKey, b64ToU8(b64(ct)));
  const roundTrip = JSON.parse(new TextDecoder().decode(decrypted));
  if (JSON.stringify(roundTrip) !== JSON.stringify(DEV_CONFIG)) {
    throw new Error('自检失败：解密结果与 DEV_CONFIG 不一致');
  }

  writeFileSync(join(__dirname, '..', 'src', 'core', 'devmode-blob.js'), out);
  console.log('✅ devmode-blob.js generated (自检通过)');
  console.log('   pwHash:', pwHash);
  console.log('   ct bytes:', ct.length, '(含 16B GCM tag)');
}

main().catch(e => { console.error('❌ 生成失败：', e.message || e); process.exit(1); });
