// scripts/gen-devmode.js
// 生成开发者模式的加密配置 blob（AES-256-GCM + PBKDF2，与浏览器 WebCrypto 完全兼容）
//
// 用法：
//   node scripts/gen-devmode.js
//   （密码与配置在下方 DEV_PASSWORD / DEV_CONFIG 中修改，重跑即可重新生成）
//
// 输出：src/core/devmode-blob.js （自动生成，勿手改）
import { webcrypto as crypto } from 'node:crypto';
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ========== 在这里改密码和配置 ==========
const DEV_PASSWORD = 'REPLACE-WITH-YOUR-STRONG-PASSWORD';
const DEV_CONFIG = {
  name: 'Agnes Dev',
  baseUrl: 'https://api.agnes-ai.cn/v1',
  apiKey: 'sk-YOUR-LLM-API-KEY',
  model: 'agnes-3.0-flash',
  visionModel: 'agnes-3.0-flash',
  reasoningEffort: 'medium', // low | medium | high
};
// ========================================

const PBKDF2_ITERATIONS = 150_000;
const PW_HASH_PREFIX = 'yks-dm-v1:';

const enc = new TextEncoder();

async function sha256Hex(str) {
  const h = await crypto.subtle.digest('SHA-256', enc.encode(str));
  return [...new Uint8Array(h)].map(b => b.toString(16).padStart(2, '0')).join('');
}

async function main() {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));

  const keyMaterial = await crypto.subtle.importKey('raw', enc.encode(DEV_PASSWORD), 'PBKDF2', false, ['deriveKey']);
  const key = await crypto.subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: PBKDF2_ITERATIONS, hash: 'SHA-256' },
    keyMaterial,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt']
  );

  const plaintext = enc.encode(JSON.stringify(DEV_CONFIG));
  const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, plaintext));

  const b64 = (u8) => Buffer.from(u8).toString('base64');
  const pwHash = await sha256Hex(PW_HASH_PREFIX + DEV_PASSWORD);

  const out = `// src/core/devmode-blob.js
// AUTO-GENERATED by scripts/gen-devmode.js — DO NOT EDIT MANUALLY
// 重新生成：修改 scripts/gen-devmode.js 中的 DEV_PASSWORD / DEV_CONFIG 后运行 node scripts/gen-devmode.js
export const DEV_BLOB = {
  saltB64: ${JSON.stringify(b64(salt))},
  ivB64: ${JSON.stringify(b64(iv))},
  ctB64: ${JSON.stringify(b64(ct))},
  pwHash: ${JSON.stringify(pwHash)},
  iterations: ${PBKDF2_ITERATIONS},
};
`;
  writeFileSync(join(__dirname, '..', 'src', 'core', 'devmode-blob.js'), out);
  console.log('✅ devmode-blob.js generated');
  console.log('   pwHash:', pwHash);
  console.log('   ct bytes:', ct.length, '(含 16B GCM tag)');
}

main().catch(e => { console.error(e); process.exit(1); });
